import { expect, it } from "vitest";
import {
  readArtifactReport,
  boundedBody,
} from "../src/services/artifact-report.service.js";
const fixtures = {
  valid:
    "UEsDBBQAAAAIAGyzLF3XMWV6ZQAAAKIAAAAZAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvbo2MMQ6AIAxFr2I6u7g6eg3D0ECjxNASW1wMdxf0Anb6//283oBmlLLBPEzjALpjS4A/D5pCfMVTOBH3J+Bjh0n8QWGRwgHPSNqW1TVupPaWGxgTdUHjxiV3SYp5+WBGVQpQXX0AUEsBAhQDFAAAAAgAbLMsXdcxZXplAAAAogAAABkAAAAAAAAAAAAAAIABAAAAAHZlbGFtZW50LXRlc3QtcmVwb3J0Lmpzb25QSwUGAAAAAAEAAQBHAAAAnAAAAAAA",
  missing:
    "UEsDBBQAAAAIAGyzLF1Dv6ajBAAAAAIAAAAKAAAAb3RoZXIuanNvbquuBQBQSwECFAMUAAAACABssyxdQ7+mowQAAAACAAAACgAAAAAAAAAAAAAAgAEAAAAAb3RoZXIuanNvblBLBQYAAAAAAQABADgAAAAsAAAAAAA=",
  oversize:
    "UEsDBBQAAAAIAGyzLF3EsdpmCQEAAAHoAwAZAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvbu3BMQEAAADCoNqLbwhfoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAATgNQSwECFAMUAAAACABssyxdxLHaZgkBAAAB6AMAGQAAAAAAAAAAAAAAgAEAAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvblBLBQYAAAAAAQABAEcAAABAAQAAAAA=",
  duplicate:
    "UEsDBBQAAAAIAGyzLF3XMWV6ZQAAAKIAAAAZAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvbo2MMQ6AIAxFr2I6u7g6eg3D0ECjxNASW1wMdxf0Anb6//283oBmlLLBPEzjALpjS4A/D5pCfMVTOBH3J+Bjh0n8QWGRwgHPSNqW1TVupPaWGxgTdUHjxiV3SYp5+WBGVQpQXX0AUEsDBBQAAAAIAGyzLF3XMWV6ZQAAAKIAAAAZAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvbo2MMQ6AIAxFr2I6u7g6eg3D0ECjxNASW1wMdxf0Anb6//283oBmlLLBPEzjALpjS4A/D5pCfMVTOBH3J+Bjh0n8QWGRwgHPSNqW1TVupPaWGxgTdUHjxiV3SYp5+WBGVQpQXX0AUEsBAhQDFAAAAAgAbLMsXdcxZXplAAAAogAAABkAAAAAAAAAAAAAAIABAAAAAHZlbGFtZW50LXRlc3QtcmVwb3J0Lmpzb25QSwECFAMUAAAACABssyxd1zFlemUAAACiAAAAGQAAAAAAAAAAAAAAgAGcAAAAdmVsYW1lbnQtdGVzdC1yZXBvcnQuanNvblBLBQYAAAAAAgACAI4AAAA4AQAAAAA=",
};
it("parses bounded reports with a backend-owned run ID", async () => {
  const report = await readArtifactReport(
    Buffer.from(fixtures.valid, "base64"),
    "a".repeat(24),
  );
  expect(report.runId).toBe("a".repeat(24));
  expect(report.tests[0]?.name).toBe("signup");
});
it.each(["missing", "oversize", "duplicate"] as const)(
  "rejects %s archives",
  async (key) => {
    await expect(
      readArtifactReport(Buffer.from(fixtures[key], "base64"), "a".repeat(24)),
    ).rejects.toThrow();
  },
);
it("limits downloaded bytes", async () => {
  await expect(
    boundedBody(new Response(new Uint8Array(2000001))),
  ).rejects.toThrow();
});
